name: "Pull Request Changelog Enforcement Workflow"
on:
  pull_request:
    # The specific activity types are listed here to include "labeled" and "unlabeled" since the enforcer allows for skipping enforcement of the changelog being edited via the "skipLabels" property
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request 
  changelog:
    runs-on: ubuntu-latest
    steps:
    # The checkout step is required since this action uses local git commands to enforce the changelog
    - uses: actions/checkout@v2
    - uses: dangoslen/changelog-enforcer@v2
